name: Rad Kernel Build

on:
  workflow_dispatch:
    inputs:
      KERNEL_REPO:
        description: 'KERNEL_REPO'
        required: true
        default: 'https://github.com/cly-build/kernel_xiaomi_vayu.git'
      KERNEL_BRANCH:
        description: 'KERNEL_BRANCH'
        required: true
        default: 'tiramisu'
      KERNEL_DEFCONFIG:
        description: 'KERNEL_DEFCONFIG'
        required: true
        default: 'vayu_defconfig'

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: self-hosted
    permissions:
      contents: write
    steps:

    - name: Prepare Env ðŸ’¤
      run: |
        sudo apt update  &> /dev/null
        sudo apt -y install gawk aria2 git ccache automake flex lzop bison gperf build-essential zip curl zlib1g-dev gcc-multilib g++-multilib libxml2-utils bzip2 libbz2-dev libbz2-1.0 libghc-bzlib-dev squashfs-tools pngcrush schedtool dpkg-dev liblz4-tool make optipng maven libssl-dev pwgen libswitch-perl policycoreutils minicom libxml-sax-base-perl libxml-simple-perl bc libc6-dev-i386 lib32ncurses5-dev libx11-dev lib32z-dev libgl1-mesa-dev xsltproc unzip device-tree-compiler python2 python3 &> /dev/null
        git config --global user.name "builder"
        git config --global user.email "delta@builder.com"
        mkdir -p $GITHUB_WORKSPACE/project
          
    - name: Prepare TC ðŸ’¦
      run: |
        mkdir -p $GITHUB_WORKSPACE/project/clang
        CLANG_URL=$(curl -Ls https://raw.githubusercontent.com/ZyCromerZ/Clang/main/Clang-14-link.txt)
        aria2c $CLANG_URL &> /dev/null
        tar -C $GITHUB_WORKSPACE/project/clang/ -zxf ${CLANG_URL##*/}

    - name: Prepare Kernel ðŸ¤
      run: |
        cd $GITHUB_WORKSPACE/project
        git clone -b ${{ github.event.inputs.KERNEL_BRANCH }} ${{ github.event.inputs.KERNEL_REPO }} linux --recurse-submodules --depth=1 &> /dev/null
        git clone -b master https://github.com/clyfly/AnyKernel3.git AnyKernel3 --depth=1 &> /dev/null

    - name: Build Kernel and Save Log â¤ï¸â€ðŸ”¥
      run: |
        cd $GITHUB_WORKSPACE/project/linux
        PATH=$GITHUB_WORKSPACE/project/clang/bin:$PATH
        export TZ="Asia/Jakarta"
        export DATE=$(date "+%Y%m%d-%H%M")
        echo "BUILD_DATE=$(date "+%Y%m%d%H%M")" >> $GITHUB_ENV
        export ARCH=arm64
        export KBUILD_BUILD_HOST=YourWaifu
        export KBUILD_BUILD_USER=Radinka
        export KBUILD_COMPILER_STRING="$(clang --version | head -n 1 | perl -pe 's/\(http.*?\)//gs' | sed -e 's/  */ /g' -e 's/[[:space:]]*$//')"
        echo "-RadVayu" > localversion
        make O=out ARCH=$ARCH ${{ github.event.inputs.KERNEL_DEFCONFIG }}
        make -j$(nproc --all) O=out CC=clang ARCH=$ARCH CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1 LD=ld.lld NM=llvm-nm AR=llvm-ar OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump > $GITHUB_WORKSPACE/buildlog.txt 2>&1 || true
        cp out/arch/arm64/boot/Image.gz-dtb $GITHUB_WORKSPACE/project/Image.gz-dtb
        wget https://gist.githubusercontent.com/zainarbani/2b482e9e9c415a644953397b6ba5571f/raw/b66cf8d0683b5397fc1f7cc6b33ff12cc9bf9292/ksu.patch
        git apply ksu.patch || exit
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -
        make O=out ARCH=$ARCH ${{ github.event.inputs.KERNEL_DEFCONFIG }}
        make -j$(nproc --all) O=out CC=clang ARCH=$ARCH CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnueabi- LLVM=1 LLVM_IAS=1 LD=ld.lld NM=llvm-nm AR=llvm-ar OBJCOPY=llvm-objcopy OBJDUMP=llvm-objdump > $GITHUB_WORKSPACE/buildlog.txt 2>&1 || true
        cp out/arch/arm64/boot/Image.gz-dtb $GITHUB_WORKSPACE/project/Image.gz-dtb-ksu

    - name: Prepare AK3 ðŸ’–
      run: |
        cd $GITHUB_WORKSPACE/project/AnyKernel3
        cp $GITHUB_WORKSPACE/project/Image.gz-dtb Image.gz-dtb
        zip -r9 $GITHUB_WORKSPACE/project/Focalors.zip -- *
        cp $GITHUB_WORKSPACE/project/Image.gz-dtb-ksu Image.gz-dtb
        zip -r9 $GITHUB_WORKSPACE/project/Focalors-KSU.zip -- *

    - name: Upload Build Log and Release ðŸ¤–
      uses: actions/upload-artifact@v2
      with:
        name: build-log
        path: $GITHUB_WORKSPACE/buildlog.txt

    - name: Upload Release ðŸ‘¾
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ${{ github.workspace }}/project/Focalors.zip
          ${{ github.workspace }}/project/Focalors-KSU.zip
          ${{ github.workspace }}/build-log/buildlog.txt
        name: RadKernel-${{ env.BUILD_DATE }}
        tag_name: ${{ env.BUILD_DATE }}
        body: |
          Repo: ${{ github.event.inputs.KERNEL_REPO }}
          Branch: ${{ github.event.inputs.KERNEL_BRANCH }}
          Config: ${{ github.event.inputs.KERNEL_DEFCONFIG }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Send Build Log to Telegram ðŸ’¯
      if: always()  # This step will run even if previous steps fail
      run: |
        curl -F "document=@$GITHUB_WORKSPACE/buildlog.txt" "https://api.telegram.org/bot${{ secrets.BOT_TOKEN }}/sendDocument?chat_id=${{ secrets.CHAT_ID }}"
